cfpb/sheer

- sheer/query.py
To make it easier to inspect objects from within templates, this returns the `_source` data when __str__ is called.
> Add string representation for QueryHit object

- sheer/query.py
Previously, search_with_url_filters(), what is primarily used for running ElasticSearch queries from within a template, only took in the standard arguments from elasticsearch-py's search() method.  Filtering was not one of those, so we were forced to use queries instead of filters for our data (slower, not the right way to do things).
Now, filters can be entered as arguments into search_with_url_filters() using the same syntax as URL filters:
`filter_range_fieldname_operator` for range filters
`filter_fieldname` for bool filters
Caveat: these continue to use the "should" option of combined filters.  This means they are treated as OR.  For more complex filters (AND, NOT, etc.), use a raw query in /_queries/
> allow filter_ syntax as arguments in template queries

- sheer/filters.py
- sheer/test_filters.py
Previously, all non-range ElasticSearch filters were being thrown into an OR filter.  A result would just have to satisfy any one of the filter choices to be returned.
If you're filtering blog posts by different fields (author, tags, date), those should be joined by an AND filter.  The set returned should satisfy all of those constraints.  Within a particular field (for example, multiple authors), that filter should be joined by an OR filter.  Each blog post returned should be written by one of the authors selected.
If that explanation sounds good, then this PR is for you!
> Reworked bool filters to make more sense for real world usage

- sheer/query.py
NOTE: There is a complementary cfgov-refresh PR that should be merged at the same time as this one: https://github.com/cfpb/cfgov-refresh/pull/285
Facets are deprecated in ElasticSearch and will be removed in a future release.  This migrates them to aggregations which work pretty much the same way as facets.
Sites that previously used terms facet with sheer will need to make slight modifications to their code.  The iterable that is returned by possible_values_for now looks like {"key": "term-you-want"} instead of {"term": "term-you-want"}.
> Switch out term facets for aggregations

- requirements.txt
- sheer/indexer.py
- sheer/scripts/sheer
- sheer/test_indexing.py
This PR adds partial indexing to Sheer. It does this by slightly changing the behavior of `sheer index`. Before this PR, if the index already existed `sheer index` would destroy the existing index in Elasticsearch, recreate it, then fetch documents from each content processor and add them to Elasticsearch. After this PR, if the index does not exist, `sheer index` behaves exactly as before. If it *does* exist: 
- `sheer index` If the index *does* exist, it will be left alone, and content will be [updated](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-update.html) 
- `sheer index --reindex` If the index *does* exist, it will be deleted and recreated, and all content refetched.
- `sheer index --processors [content processor] [content processor] ...` 
- If the …
> Partial indexing and reindexing

- sheer/views.py
Primarily, this is so that we don't expose directories like .git and _settings
> Web app now keeps clients from accessing dirs that begin with . or _

- sheer/wsgi.py
**Additions**
- Sanity
**Removals**
- Removed the use of the terminal bell 
**Changes**
- The mental landscape of serving content with Sheer. 
**Testing**
- Run `sheer serve`. Visit http://localhost:7000. Enjoy silence as you browse.
**Review**
- @dpford 
- @rosskarchner 
**Preview**
Imagine yourself in a room without bells.
**Notes**
- I know I can disable the bell. I can't disable the little red notification dot on Terminal.app. If there are good reasons for the bell, we can close this, but I'm having trouble imagining them.
> Remove the bell

- sheer/indexer.py
- sheer/test_indexing.py
This PR handles ValueErrors that occur during indexing more gracefully. ValueErrors may be thrown by content processors when `json.loads()` is unable to parse JSON that's received. That could be because of errors on the side providing the JSON, or because of malformed JSON being returned. In either case, before this change Sheer would bail completely. This PR will have Sheer print an error to stderr and then continue on to the next content processor, so the indexing process as a whole does not fail, just the indexing process for the content processor that's experiencing the error.
**Changes**
- Gracefully handle ValueErrors raised by content processors during indexing.
**Testing**
- `nodetests` from the root of the repository
- `nodetests sheer/test_indexing.py` from the root of the …
> Gracefully handle JSON ValueErrors when Indexing

- LICENSE
- README.md
- sheer/scripts/sheer
This PR is a significant overhaul of the Sheer README with the goal of making it clearer what Sheer does and can be used for, and how to use it (API documentation both for python developers and for front-ends). This includes a lot of the same information as the old README, but in some different places. 
It removes the section about Jekyll because, honestly, coming to Sheer for the first time that certainly confused me, because however Sheer might have begun life it's a very different beast from Jekyll right now. 
I've also provided some links to Elasticsearch documentation interspersed with the content, since Sheer uses Elasticsearch relatively transparently.
@dpford contributed to this while it was in the wiki. I welcome any other suggestions on how to make Sheer more understandable. …
> Bring text from "Understanding Sheer" wiki page into README

- README.md
Of course I forgot to push this up to my Github fork yesterday after my other changes before #94 was merged. 
This just a minor semantic change: Elasticsearch is required to *run* Sheer, but not to *install* it.
> Minor Semantic correction to README: ES is needed to run, not install, Sheer

- sheer/feeds.py
Werkzeug Atom feeds require date types to be in datetime.datetime format, so this makes that conversion when necessary.   This also fixes an issue where the URL for the main feed wasn't correct.
Review: @willbarton @kurtw
How to test:
1. Checkout [this](https://github.com/cfpb/cfgov-refresh/pull/437) PR
2. Navigate to /feed/posts/ and /feed/newsroom/
> Convert date to datetime object before passing into feed

- requirements.txt
After the pbr conversion, running `pip install -e . --upgrade` was breaking on certain environments without a version specified for itsdangerous.  This fixes that problem.
> Specified version for itsdangerous

- sheer/indexer.py
- sheer/test_indexing.py
Currently, when an Elasticsearch mapping isn't specified in the `processors.json` file, a default mapping is set (found in /_defaults/).  This might have made sense back when we had a single post type, but now that we have a number of different post types with varying fields, this seems wrong.  
We should still create an explicit mapping for each doc_type, but let Elasticsearch take its best guess at a mapping in the absence of a supplied one, rather than use an incorrect mapping not meant for that doc_type.
Review: @rosskarchner @Scotchester @willbarton
> Remove default ES mapping functionality

- sheer/indexer.py
- sheer/test_indexing.py
Sheer consumes a `_settings/processors.json` file, indexing each doc type.  Currently, if one of the doc types fails, an error message is printed to stderr and the process continues.  This is particularly problematic when using something like Jenkins, because even though some of the doc types may have failed, the build will still be labeled as a success.  If it weren't for a proactive developer skimming through the output, the unindexed doc type might go unnoticed.
In this PR, we now keep track of the failing processors (if any), and exit with an exit code describing the problem.  A user running `sheer index` should see the failure message at the end, and Jenkins will know to fail the build if everything didn't index properly.  If everything indexes properly, the behavior is exactly like …
> Include a non-zero exit code if indexing fails

- requirements.txt
- sheer/indexer.py
- sheer/test_indexing.py
WARNING: This is a breaking update, which requires a slight tweak to processor files.  Those PRs (which I'll also be making) should be merged in at the same time as this update, and will be listed here shortly.
Two main changes:
According to the [docs](https://elasticsearch-py.readthedocs.org/en/master/#compatibility), we have been using the wrong version.  Since we're all using Elasticsearch > 1.0, we need to be using a 1.X.X version of the python elasticsearch wrapper.
**Please `pip install -r requirements.txt`**
Previously, we were making a request for each document we were indexing.  With this PR, we now use bulk indexing to do it in one go (to be exact, in larger [chunks](http://elasticsearch-py.readthedocs.org/en/latest/helpers.html#elasticsearch.helpers.bulk), but the same idea …
> Use Elasticsearch bulk indexing

- sheer/wsgi.py
This template filter converts the output of `possible_values_for` to a list, making it possible to check if an item is in an aggregation, from within the template.
(As a reminder, `possible_values_for` returns all the values for a given field, and the number of occurrences of each)
Review: @kurtw
> Add template filter to convert possible_values_for to a list

- sheer/wsgi.py
This adds a useful template filter to grab the domain name from a URL.  We will be using this to check to make sure external URLs actually originated from our site.
Example:
```
{% set url = "https://en.wikipedia.org/wiki/Rat_king_(folklore)" %}
{{ url | domain_name }}
```
en.wikipedia.org
> Template filter to extract domain name

- README.md
- sheer/apis/apiv1.py
- sheer/feeds.py
- sheer/query.py
When searching using search_with_url_arguments from within a template, the function will take in url arguments, as well as arguments from the function. This adds a parameter to flag if that behavior is desired. The name of the function has also been changed, and needs to be updated in the repo's that use it: [cfgov-refresh](https://github.com/cfpb/cfgov-refresh), [owning-a-home](https://github.com/cfpb/owning-a-home/blob/master/src/process/_process-step.html)
@dpford @rosskarchner
> Fix template search bug, change name of function, remove unnecessary lines

- requirements.txt
- sheer/templates.py
- sheer/wsgi.py
You must run a `pip install -r requirements.txt` to grab the pytz package this introduces as a dependency.
Timezones are a pain. This makes it so you can pass the name of a timezone and it will be able to create a timestamp much like this `MAR 12, 2001 6:15 AM CST`
Pass in a ISO8601 timestamp and a timezone name to the `date()` filter in jinja2. If the output is like the example above then success!
@jimmynotjim @dpford @rosskarchner
> Add timezone to dateformat function

- sheer/query.py
This adds a new function to the context called `when`. It takes two parameters: `starttime` and `endtime`. It is meant to figure out if the time period (between starttime and endtime) is in the past, present, or future. Actually, those are the strings it returns: `'past'/'present'/'future'`.
This requires the package pytz. You have to run `pip install -r requirements.txt` in order for this to work.
@dpford @rosskarchner
> Add when function to the context
